"""
Chapter 3 - Monte Carlo Methods
Exercise 1

Notes: notes/ch03-monte-carlo-methods/exercises.md

Part (c): Simulate 100 independent draws of [X, Y]^T uniformly distributed on
the unit disc, using X = R*cos(Theta), Y = R*sin(Theta), with
Theta ~ U(0, 2*pi) and R generated by inverse-transform from
F_R(r) = r^2 for 0 <= r <= 1 (so F_R^{-1}(u) = sqrt(u)).
"""

import numpy as np
import matplotlib.pyplot as plt

n = 100
U = np.random.rand(n)
Theta = np.random.rand(n) * 2*np.pi
R = np.sqrt(U)  # inverse-transform: F_R(r) = r^2  =>  F_R^{-1}(u) = sqrt(u)
X = R*np.cos(Theta)
Y = R*np.sin(Theta)

plt.scatter(X, Y, s=10)
plt.gca().set_aspect('equal')
theta_circle = np.linspace(0, 2*np.pi, 200)
plt.plot(np.cos(theta_circle), np.sin(theta_circle), 'r--', linewidth=1)
plt.xlabel('X')
plt.ylabel('Y')
plt.title('100 points uniform on the unit disc')
plt.show()
